### PR TITLE
Fix/ccache

### PR DESCRIPTION
**Pull request by Yuhanun**
It's some issue with the path, not sure if this is only the path for me or for everyone (I wrote this when I was on archlinux.)

### CODE REVIEW

**Comment by rolfvdhulst** [comment]
Your commit is fine, but what are these other older commits doing and why do you want to merge them?
The optimization flags and robotcommands are different on a low level here so I don't know if this still works properly.

**Comment by Yuhanun** [comment]
I didn't actually commit these, I just branched from development. Not sure how they got in here, what should I do?

**Comment by rolfvdhulst** [comment]
Your pull request is to master, that's the problem then

**Comment by rolfvdhulst** [comment]
Just change the PR to merge to development

**Pull request merged**
